### PR TITLE
fix(view): fix $animate usage for 1.4+

### LINKED ISSUE #1959: angular-animate master no longer allows callbacks.
Using the master branches of ui-router and angular (1.4.x).

Please fix asap.

```
Error: [$animate:nocb] Do not pass a callback to animate methods
http://errors.angularjs.org/1.3.16-build.111+sha.0515614/$animate/nocb
    at http://localhost:3000/bower_components/angular/angular.js:63:12
    at Object.$$assertNoCallback (http://localhost:3000/bower_components/angular/angular.js:4684:17)
    at parseAnimateOptions (http://localhost:3000/bower_components/angular-animate/angular-animate.js:558:21)
    at Object.enter (http://localhost:3000/bower_components/angular-animate/angular-animate.js:955:21)
    at Object.enter (http://localhost:3000/bower_components/angular-ui-router/release/angular-ui-router.js:3855:34)
    at http://localhost:3000/bower_components/angular-ui-router/release/angular-ui-router.js:3929:22
    at publicLinkFn (http://localhost:3000/bower_components/angular/angular.js:7039:29)
    at updateView (http://localhost:3000/bower_components/angular-ui-router/release/angular-ui-router.js:3928:23)
    at http://localhost:3000/bower_components/angular-ui-router/release/angular-ui-router.js:3896:9
    at invokeLinkFn (http://localhost:3000/bower_components/angular/angular.js:8302:9) <!-- uiView: undefined --
```

### PR DESCRIPTION
**Pull request by wesleycho**
This fixes #1959

### CODE REVIEW

File: src/viewDirective.js [hunk 1]
```diff
@@ -143,12 +143,14 @@ function $ViewDirective(   $state,   $injector,   $uiViewScroll,   $interpolate)
...
-          var promise = $animate.enter(element, null, target, cb);
-          if (promise && promise.then) promise.then(cb);
+          var promise = (angular.version.minor > 2) ?
+            $animate.enter(element, null, target).then(cb) :
+            $animate.enter(element, null, target, cb);
         },
         leave: function(element, cb) {
-          var promise = $animate.leave(element, cb);
-          if (promise && promise.then) promise.then(cb);
+          var promise = (angular.version.minor > 2) ?
```
Comment (christopherthielen) [inline src/viewDirective.js]: is the `promise` variable doing anything?

Comment (wesleycho) [inline src/viewDirective.js]: Oh good point, I'll remove it.

**Comment by Foxandxss** [comment]
:+1:
